version: '2'

### Change the `project` with your own project name ###
services:
    application:
        container_name: qlns_application
        image: debian
        volumes:
            - ./:/var/www/laravel
    workspace:
        container_name: qlns_workspace
        restart: always
        image: framgia/laravel-workspace
        volumes_from:
            - application
        tty: true
    php-fpm:
        container_name: qlns_php-fpm
        restart: always
        image: framgia/laravel-php-fpm
        volumes_from:
            - application
        expose:
            - "9000"
        links:
            - workspace
    nginx:
        container_name: qlns_nginx
        restart: always
        image: framgia/laravel-nginx
        volumes_from:
            - data
            - logs
            - application
        ports:
            - "8000:80"
        links:
            - php-fpm
    data:
        container_name: qlns_data
        image: debian
        volumes:
            - .docker/mysql:/var/lib/mysql
            - .docker/data:/data
    data_test:
        container_name: qlns_data_test
        image: debian
        volumes:
            - .docker/mysql_test:/var/lib/mysql
            - .docker/data_test:/data
    logs:
        container_name: qlns_logs
        image: debian
        volumes:
            - .docker/logs/nginx:/var/log/nginx
            - .docker/logs/mongodb:/var/log/mongodb
    mysql:
        container_name: qlns_mysql
        image: mysql
        volumes_from:
            - data
            - logs
        expose:
            - "3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
    mysql_test:
        container_name: qlns_mysql_test
        restart: always
        image: mysql
        volumes_from:
            - data_test
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: homestead_test
            MYSQL_USER: homestead_test
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
    mongo:
        container_name: qlns_mongo
        restart: always
        image: mongo
        expose:
            - "27017"
        volumes_from:
            - data
            - logs
    redis:
        container_name: qlns_redis
        restart: always
        image: redis
        expose:
            - "6379"
        volumes_from:
            - data
